- hosts: all
  vars_files:
    - vars.yaml
  tasks:

    - include: install_dev_dependencies.yaml
    - include: firewall.yaml
    - include: setup_mlflow.yaml

    I found, that restarting fixes conda and environments
    - name: restart
      become: true
      reboot:
  
  # - import_playbook: install_https_custom.yaml
  # - import_playbook: install_https_lets_encrypt.yaml