
[frontends.frontend_mlflow]
    entryPoints = ["mlflow"]
    backend = "backend_mlflow"

[frontends.frontend_mlflow.routes.test]
    rule = "PathPrefix:/"


[backends.backend_mlflow.servers.server1]
    url = "http://127.0.0.1:5000"
    weight = 1